version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
    volumes:
      - "c:/Users/Attila_Szabo1/jenkins:/var/jenkins_home"
